BEGIN;

CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text not null,
    amount int not null,
    Stock int not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

COMMIT;
