BEGIN;

CREATE TABLE IF NOT EXISTS customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text,
    created_at timestamp not null,
    updated_at timestamp not null
);

COMMIT;
