BEGIN;

CREATE TABLE IF NOT EXISTS customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text not null,
    first_name text,
    last_name text,
    balance int,
    created_at timestamp not null,
    updated_at timestamp not null
);

CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text not null,
    amount int not null,
    Stock int not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

CREATE TABLE IF NOT EXISTS cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint references customers(id) on delete cascade not null,
    product_id bigint references products(id) not null,
    product_title text not null,
    amount int not null,
    quantity int not null,
    is_valid boolean,
    created_at timestamp not null,
    updated_at timestamp not null
);

COMMIT;
