BEGIN;

CREATE TABLE IF NOT EXISTS customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text not null,
    first_name text,
    last_name text,
    balance int,
    created_at timestamp not null,
    updated_at timestamp not null
);

COMMIT;
