version: 0.1.0
base_dir: $PWD
main_domain: "xxx"
db:
  user: postgres
  password: password
  name: micro_ecommerce
  port: 5434
  sslmode: disable
  host: minikube-host.default.svc.cluster.local
rocketmq:
  host: minikube-host.default.svc.cluster.local
  name_server_port: 9876
  broker_port: 10911
redis:
  endpoint: "127.0.0.1"
  password: "123456"
  port: "6380"
jwt_secret: "xxx"
