version: 0.1.0
base_dir: $PWD
main_domain: "xxx"
db:
  user: postgres
  password: password
  name: micro_ecommerce
  port: 5434
  sslmode: disable
  host: localhost
redis:
  endpoint: "127.0.0.1"
  password: "123456"
  port: "6380"
jwt_secret: "xxx"
migration_path: "/Users/smiletrl/go/src/github.com/smiletrl/micro_ecommerce/migrations"
