apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cart-external
  namespace: ${env}
spec:
  gateways:
  - api-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        exact: /api/v1/cart_item
    route:
    - destination:
        host: cart
        port:
          number: 1325
